spring:
  application:
    name: demo

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${app.jwt.public-key}

app:
  jwt:
    public-key: classpath:public.pem
    private-key: classpath:private_key.pem
